### ISSUE TITLE
Please have the link label dataset with the dataset?

### ISSUE THREAD

**Issue by tphankr** [tancalv2/ConfettiRemoval#3]
When I downloaded the dataset from the link, as following, only have the rain image inputs but do not have labels. Please help have them.
![image](https://user-images.githubusercontent.com/37217354/129291507-1a2cd138-78d6-4638-ae27-7ee525b737b0.png)
![image](https://user-images.githubusercontent.com/37217354/129291603-46438172-55e2-4c5a-b31e-80293543e077.png)

Thank you.

**Comment by tancalv2** [comment]
We do not own this dataset since these images are from the authors of LPNet. Please contact them for specific dataset inquires. 

On a side note, as these are real-world images, there are no such 'labels' for these images.

**Comment by tphankr** [comment]
Thank you @tancalv2.
If do not have label for these image. I can not training likely  the paper.

Thank you @tancalv2
